from pathlib import Path
p=Path(r'C:\Users\Abu\Documents\Python\CornerWork\extension-demo')
f=p/'core.js';s=f.read_text();s=s.replace("if(!body)throw Error('Enter a transcript.');", "const audio=payload.audio||'';if(audio && (!/^data:audio\\/(webm|ogg|mp4|mpeg|wav|x-wav)(;codecs=[^;,]+)?;base64,[A-Za-z0-9+/=]+$/.test(audio)||audio.length>1100000))throw Error('Use a supported audio clip smaller than 800 KB.');if(!body&&!audio)throw Error('Record a voice note or enter a message.');")
s=s.replace("id:site.logs.length+1,body,reply:''", "id:site.logs.length+1,body,audio,reply:''")
f.write_text(s)
f=p/'index.html';s=f.read_text().replace('Pings and voice notes are simulated. No real messages are sent.','Pings are simulated. Voice recordings stay in this browser. No real messages are sent.').replace('This is a typed voice-note transcript, not microphone recording.','Record a real voice note below, or type a message. Audio stays on this device; there is no automatic transcription.')
s=s.replace('<label for="note">3. Ask the coach for advice</label>','<h3>3. Ask the coach for advice</h3><div class="row"><button type="button" id="record">Record voice note</button><button type="button" id="stop-record" disabled>Stop recording</button><button type="button" id="discard-record" class="secondary" disabled>Discard audio</button></div><p id="voice-status" role="status">Up to 45 seconds. Your browser will ask for microphone access.</p><audio id="voice-preview" controls hidden></audio><label for="audio-file">Or choose a short audio file (max 800 KB)</label><input id="audio-file" type="file" accept="audio/webm,audio/ogg,audio/mp4,audio/mpeg,audio/wav,audio/x-wav"><label for="note">Optional text / manually typed transcript</label>')
s=s.replace('I lose my balance after the jab-cross. What should I practise before the next class?</textarea>','</textarea>').replace('Send simulated voice note','Send to coach queue').replace('<script src="lab.js"></script>','<script src="voice.js"></script><script src="lab.js"></script>');f.write_text(s)
f=p/'lab.js';s=f.read_text().replace("act('note',{body:$('#note').value})", "try{if(Voice.busy())throw Error('Stop recording before sending.');if(Voice.provider()&&Voice.provider()!==CW.read().provider)throw Error('The provider changed. Discard this audio and record again.');CW.update('note',{body:$('#note').value,audio:Voice.audio()});Voice.clear();$('#note').value='';render();$('#status').textContent='Sent to the local coach queue.'}catch(err){$('#status').textContent=err.name==='QuotaExceededError'?'Local storage is full. Reset an old fictional scenario or use a shorter recording. Your draft is still available.':err.message}")
f.write_text(s)
f=p/'panel.js';s=f.read_text().replace('Today · simulated voice-note transcript','Today · local member message').replace("'<p class=", "'<p class=")
s=s.replace("esc(l.body)+'</p>'", "esc(l.body||'Voice note — listen below; no automatic transcript.')+'</p>'+(l.audio?'<audio controls preload=\"metadata\" src=\"'+esc(l.audio)+'\"></audio>':'')")
s=s.replace("esc(l.body)+'</p><strong>'", "esc(l.body||'Voice note — no automatic transcript.')+'</p>'+(l.audio?'<audio controls preload=\"metadata\" src=\"'+esc(l.audio)+'\"></audio>':'')+'<strong>'")
f.write_text(s)
f=p/'panel.html';s=f.read_text().replace('No live account access, SMS, audio transcription or AI.','Real local audio playback; no live account access, SMS, automatic transcription or AI.');f.write_text(s)
(p/'voice.js').write_text('''let recorder=null,stream=null,timer=null,draft='',draftProvider='',previewURL='',pending=false;
const voiceStatus=t=>document.querySelector('#voice-status').textContent=t;
function cleanup(){clearTimeout(timer);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;}
function buttons(){document.querySelector('#record').disabled=pending||!!recorder;document.querySelector('#stop-record').disabled=!recorder||recorder.state!=='recording';document.querySelector('#discard-record').disabled=!draft||pending||!!recorder;document.querySelector('#audio-file').disabled=pending||!!recorder;}
function clearDraft(){draft='';draftProvider='';const a=document.querySelector('#voice-preview');a.pause();a.removeAttribute('src');a.hidden=true;if(previewURL)URL.revokeObjectURL(previewURL);previewURL='';document.querySelector('#audio-file').value='';buttons();}
async function acceptBlob(blob,provider){if(blob.size>800000)throw Error('Clip is too large. Use a shorter recording (max 800 KB).');if(!blob.size)throw Error('The recording is empty. Try again.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read audio.'));r.readAsDataURL(blob)});if(!/^data:audio\\/(webm|ogg|mp4|mpeg|wav|x-wav)(;codecs=[^;,]+)?;base64,/.test(data))throw Error('Unsupported audio format. Try WebM, Ogg, M4A, MP3 or WAV.');clearDraft();draft=data;draftProvider=provider;previewURL=URL.createObjectURL(blob);const a=document.querySelector('#voice-preview');a.src=previewURL;a.hidden=false;voiceStatus('Audio ready. Listen, then send to the coach queue. No automatic transcript.');buttons();}
document.querySelector('#record').onclick=async()=>{if(pending||recorder)return;pending=true;buttons();const provider=CW.read().provider;try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Recording is unavailable here. Open in desktop Chrome or choose an audio file.');stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime,audioBitsPerSecond:32000}:{});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>{cleanup();recorder=null;pending=false;buttons();voiceStatus('Recording failed. Try again or choose an audio file.')};recorder.onstop=async()=>{const type=recorder?.mimeType||mime||'audio/webm';cleanup();recorder=null;pending=true;buttons();try{await acceptBlob(new Blob(chunks,{type}),provider)}catch(e){voiceStatus(e.message)}finally{pending=false;buttons()}};recorder.start();pending=false;timer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},45000);voiceStatus('Recording… press Stop when finished (45-second limit).');buttons();}catch(e){cleanup();recorder=null;pending=false;buttons();voiceStatus(e.name==='NotAllowedError'?'Microphone permission was denied. Allow it in browser settings or choose an audio file.':e.message)}};
document.querySelector('#stop-record').onclick=()=>{if(recorder?.state==='recording'){pending=true;recorder.stop();buttons();}};
document.querySelector('#discard-record').onclick=()=>{clearDraft();voiceStatus('Audio discarded. Record another or type a message.')};
document.querySelector('#audio-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;pending=true;buttons();const provider=CW.read().provider;try{await acceptBlob(file,provider)}catch(err){voiceStatus(err.message)}finally{pending=false;buttons()}};
window.addEventListener('pagehide',cleanup);
window.Voice={audio:()=>draft,provider:()=>draftProvider,busy:()=>pending||!!recorder,clear:()=>{clearDraft();voiceStatus('Voice note sent locally.')}};
''')
with (p/'style.css').open('a') as f:f.write('\naudio{width:100%;margin:10px 0}input[type=file]{max-width:100%}\n')
print('Voice recording, file attachment and queue/brief playback added.')
