from pathlib import Path
import json
p=Path(r'C:\Users\Abu\Documents\Python\CornerWork\extension-demo');p.mkdir(exist_ok=True)
files={
'manifest.json':json.dumps({'manifest_version':3,'name':'Cornerwork — fictional flow test','version':'0.1.0','minimum_chrome_version':'116','description':'Local fictional coaching flow. No Mindbody or Gymdesk connection.','permissions':['sidePanel'],'action':{'default_title':'Open Cornerwork demo'},'side_panel':{'default_path':'panel.html'},'background':{'service_worker':'background.js'},'options_page':'index.html'},indent=2),
'background.js':"chrome.runtime.onInstalled.addListener(() => { chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true}).catch(console.error); });\n",
'style.css':'''*{box-sizing:border-box}body{margin:0;background:#f4f3ed;color:#203d36;font:15px/1.5 system-ui,sans-serif}main{max-width:1160px;margin:auto;padding:24px}h1{font-size:28px;margin:8px 0}h2{font-size:19px}h3{font-size:16px;margin:8px 0}p{margin:8px 0}small,.muted{color:#5b6e64}button,select,textarea{font:inherit}button,a.button{background:#2f6554;color:white;border:0;border-radius:8px;padding:10px 13px;cursor:pointer;text-decoration:none;display:inline-block}button:disabled{opacity:.45;cursor:default}button.secondary{background:#e5e9df;color:#203d36}select,textarea{width:100%;padding:10px;border:1px solid #b8c4b8;border-radius:7px;background:white;color:#203d36}textarea{min-height:90px;resize:vertical}label{display:block;font-weight:600;margin:12px 0 5px}.notice{padding:12px;background:#fff0cb;border:1px solid #e3c377;border-radius:8px}.card{background:#fffef8;border:1px solid #d8dfd3;border-radius:12px;padding:18px;margin:14px 0}.layout{display:grid;grid-template-columns:1fr 390px;gap:24px}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.badge{font-size:12px;background:#e4ecdf;padding:4px 8px;border-radius:12px}.item{border-bottom:1px solid #e0e4db;padding:12px 0}.item:last-child{border:0}.message{padding:12px;background:#eaf0e3;border-radius:8px;white-space:pre-wrap;overflow-wrap:anywhere}iframe{width:100%;height:820px;border:1px solid #bdc9bb;border-radius:12px;background:#f4f3ed}.panel{padding:16px;max-width:600px}.panel h1{font-size:22px}nav{display:flex;gap:5px;margin:16px 0}nav button{flex:1;font-size:13px;padding:9px 5px}nav button[aria-pressed=true]{background:#203d36;color:white}#status{min-height:24px;font-size:13px;color:#345e4c}a{color:#245d4e}button:focus-visible,a:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #ba773f;outline-offset:3px}@media(max-width:760px){.layout{grid-template-columns:1fr}main{padding:14px}}''',
'core.js':'''(function(root){
const KEY='cornerwork-extension-fictional-v1';
function seed(){return {provider:'gymdesk',sites:{gymdesk:{attended:false,ping:false,logs:[]},mindbody:{attended:false,ping:false,logs:[]}}};}
function read(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch{return seed()}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));return s}
function apply(s,action,payload={}){s=JSON.parse(JSON.stringify(s));const site=s.sites[s.provider];
if(action==='provider'){if(!['gymdesk','mindbody'].includes(payload.provider))throw Error('Unknown fixture');s.provider=payload.provider;}
else if(action==='attend')site.attended=true;
else if(action==='ping'){if(!site.attended)throw Error('Check in the fictional member first.');site.ping=true;}
else if(action==='note'){if(!site.ping)throw Error('Run the post-class ping first.');const body=(payload.body||'').trim();if(!body)throw Error('Enter a transcript.');if(body.length>2000)throw Error('Keep the transcript under 2,000 characters.');site.logs.push({id:site.logs.length+1,body,reply:'',at:new Date().toISOString()});}
else if(action==='reply'){const log=site.logs.find(x=>x.id===payload.id);if(!log)throw Error('Message not found.');if(log.reply)throw Error('Already replied.');const body=(payload.body||'').trim();if(!body)throw Error('Enter a reply.');if(body.length>2000)throw Error('Keep replies under 2,000 characters.');log.reply=body;}
else if(action==='reset')s.sites[s.provider]={attended:false,ping:false,logs:[]};
else throw Error('Unknown action');return s;}
function update(action,payload){return save(apply(read(),action,payload))}
function name(provider){return provider==='mindbody'?'Mindbody':'Gymdesk'}
root.CW={KEY,seed,read,save,apply,update,name};
if(typeof module!=='undefined')module.exports=root.CW;
})(globalThis);''',
'index.html':'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cornerwork extension test lab</title><link rel="stylesheet" href="style.css"></head><body><main><span class="badge">CORNERWORK / EXTENSION TEST LAB</span><h1>Try the coaching loop beside a roster.</h1><p class="notice">Fictional fixtures only. These are not Mindbody or Gymdesk screens or integrations. Pings and voice notes are simulated. No real messages are sent.</p><div class="layout"><section><div class="card"><label for="provider">Provider scenario</label><select id="provider"><option value="gymdesk">Gymdesk — fictional scenario</option><option value="mindbody">Mindbody — fictional scenario</option></select><p class="muted">Separate test data for each scenario. The selector is manual; no website detection.</p><h2 id="roster-title"></h2><p>Monday · Beginner boxing · Coach Maya</p><div class="item"><strong>Sarah Demo</strong><p id="attendance"></p><button id="attend">1. Check Sarah in</button></div><div class="item"><strong>Alex Demo</strong><p>Booked, not attended — receives no ping in this test.</p></div><button id="ping">2. End class + simulate ping</button><p id="ping-status"></p></div><div class="card"><h2>Member phone simulator</h2><p class="muted">Sarah is a fictional, opted-in adult. This is a typed voice-note transcript, not microphone recording.</p><p id="member-ping" class="message"></p><form id="note-form"><label for="note">3. Ask the coach for advice</label><textarea id="note" maxlength="2000">I lose my balance after the jab-cross. What should I practise before the next class?</textarea><button id="send-note">Send simulated voice note</button></form><div id="replies"></div></div><div class="card"><h2>Test the actual extension</h2><p>Load this folder using Chrome's <strong>Load unpacked</strong>, open extension Options, then click the pinned Cornerwork toolbar icon. The same queue opens in Chrome's real side panel.</p><p>The panel on this page is a browser preview. When loaded as an extension, its state is separate from this HTTP preview.</p><button id="reset" class="secondary">Reset this fictional scenario</button></div><p id="status" role="status"></p></section><aside><h2>Coach sidebar preview</h2><iframe title="Cornerwork coach sidebar" src="panel.html"></iframe></aside></div></main><script src="core.js"></script><script src="lab.js"></script></body></html>''',
'lab.js':'''const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const s=CW.read(),x=s.sites[s.provider];$('#provider').value=s.provider;$('#roster-title').textContent=CW.name(s.provider)+' roster fixture';$('#attendance').textContent=x.attended?'Attended — ready for the post-class ping':'Booked — no attendance yet';$('#attend').disabled=x.attended;$('#ping').disabled=!x.attended||x.ping;$('#send-note').disabled=!x.ping;$('#ping-status').textContent=x.ping?'One simulated ping delivered to Sarah. Alex receives none.':'No pings sent.';$('#member-ping').textContent=x.ping?'Cornerwork: How did class go? Reply with a question for your coach.':'Waiting for the post-class ping.';$('#replies').innerHTML=x.logs.filter(l=>l.reply).map(l=>'<h3>Coach reply</h3><p class="message">'+esc(l.reply)+'</p>').join('');}
function act(a,p){try{CW.update(a,p);render();$('#status').textContent='Saved locally.'}catch(e){$('#status').textContent=e.message}}
$('#provider').onchange=e=>act('provider',{provider:e.target.value});$('#attend').onclick=()=>act('attend');$('#ping').onclick=()=>act('ping');$('#note-form').onsubmit=e=>{e.preventDefault();act('note',{body:$('#note').value})};$('#reset').onclick=()=>{if(confirm('Reset only this fictional provider scenario?'))act('reset')};window.addEventListener('storage',e=>{if(e.key===CW.KEY)render()});render();''',
'panel.html':'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cornerwork coach sidebar</title><link rel="stylesheet" href="style.css"></head><body><main class="panel"><span class="badge">FICTIONAL DEMO · NOT CONNECTED</span><h1>Cornerwork</h1><p>Coaching between classes.</p><label for="provider">Manual provider scenario</label><select id="provider"><option value="gymdesk">Gymdesk fixture</option><option value="mindbody">Mindbody fixture</option></select><nav aria-label="Coach views"><button id="queue" aria-pressed="true">4. Reply queue</button><button id="brief" class="secondary" aria-pressed="false">5. Next class</button></nav><div id="screen"></div><p id="status" role="status"></p><a href="index.html" target="_blank" rel="noopener">Open fictional attendance + member simulator</a><p class="muted">Local data only. No live account access, SMS, audio transcription or AI. Browser preview and installed extension use separate storage.</p></main><script src="core.js"></script><script src="panel.js"></script></body></html>''',
'panel.js':'''const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let view='queue';
function render(){const s=CW.read(),x=s.sites[s.provider];$('#provider').value=s.provider;$('#queue').setAttribute('aria-pressed',view==='queue');$('#brief').setAttribute('aria-pressed',view==='brief');if(view==='queue'){$('#screen').innerHTML='<h2>'+x.logs.filter(l=>!l.reply).length+' awaiting reply</h2>'+ (x.logs.length?x.logs.slice().reverse().map(l=>'<article class="card"><h3>Sarah Demo</h3><small>Today · simulated voice-note transcript</small><p class="message">'+esc(l.body)+'</p>'+(l.reply?'<h3>Replied</h3><p>'+esc(l.reply)+'</p>':'<form data-id="'+l.id+'"><label for="reply-'+l.id+'">Your reply</label><textarea id="reply-'+l.id+'" maxlength="2000" required></textarea><button>Send simulated reply</button></form>')+'</article>').join(''):'<p class="card">No questions yet. Check Sarah in, simulate the ping, then submit her voice-note transcript in the test lab.</p>');document.querySelectorAll('form[data-id]').forEach(f=>f.onsubmit=e=>{e.preventDefault();try{CW.update('reply',{id:Number(f.dataset.id),body:f.querySelector('textarea').value});render();$('#status').textContent='Reply saved. Check the member simulator.'}catch(e){$('#status').textContent=e.message}});}else{$('#screen').innerHTML='<h2>Wednesday · Beginner boxing</h2><p class="muted">Fictional next-class roster. Shows recent context captured in this test session, not a live provider booking.</p><article class="card"><h3>Sarah Demo</h3>'+(x.logs.length?x.logs.map(l=>'<div class="item"><strong>Question from last class</strong><p>'+esc(l.body)+'</p><strong>'+(l.reply?'Coach advice to follow up':'Still awaiting coach reply')+'</strong><p>'+esc(l.reply||'Resolve this question before class.')+'</p></div>').join(''):'<p>No feedback yet.</p>')+'</article><article class="card"><h3>Alex Demo</h3><p>No feedback recorded.</p></article>';}}
$('#provider').onchange=e=>{CW.update('provider',{provider:e.target.value});render()};$('#queue').onclick=()=>{view='queue';render()};$('#brief').onclick=()=>{view='brief';render()};window.addEventListener('storage',e=>{if(e.key===CW.KEY)render()});render();''',
'README.md':'''# Cornerwork extension flow test

Fictional, self-contained prototype. This folder does not modify the existing FastAPI demo or its database. It is NOT a Mindbody/Gymdesk integration or a reproduction of either vendor UI.

## Quick browser preview

Run `start-preview.ps1` and open http://127.0.0.1:8766. The embedded panel previews the coach UI; it is not Chrome's native sidebar. The server serves only this folder on loopback.

## Actual Chrome extension

1. Open `chrome://extensions` in desktop Chrome.
2. Enable Developer mode and choose **Load unpacked**.
3. Select `C:\\Users\\Abu\\Documents\\Python\\CornerWork\\extension-demo`.
4. Pin **Cornerwork — fictional flow test** and click it to open Chrome's real sidebar.
5. In the sidebar, click **Open fictional attendance + member simulator**. Use that extension-origin simulator, not the HTTP preview, so both share storage.
6. Select Gymdesk, check Sarah in, end class/simulate ping, and submit the typed voice-note transcript. Alex is booked but absent and receives no ping.
7. In the sidebar, reply to Sarah. Her reply appears in the member simulator.
8. Choose Next class: see Sarah's question and coach advice.
9. Select Mindbody and repeat. Each fixture has independent records. Switching providers is manual.
10. Reload: records persist. Repeat end-class clicks cannot create duplicate pings. Reset affects only the selected fictional scenario.

The extension requests only the sidePanel permission. It does not read websites, credentials, rosters or browsing history. It can sit beside a real provider webpage but that proves placement only. No data connection, account compatibility or automatic context recognition is claimed.

## Later account-backed test

With an authorized test gym account, first compare manual class selection and sidebar usability beside each actual roster. Then separately verify allowed API access, stable gym/class/member identifiers, attendance versus booking events, cancellations, time zones, opt-outs, retries and duplicate-event handling. Do not infer those from this fixture. A backend scheduler must work while Chrome is closed. Test audio capture/transcription and actual message delivery separately.

## Limits

All members are fictional opted-in adults. Pings, voice notes and replies are local records; no audio or messages are sent. The next-class brief uses this test session, not the existing demo's seven-day logic. No login, secure tenant isolation, production scheduler or cross-device synchronization. Do not enter real member data. HTTP preview and extension storage are intentionally separate.

## Verification

`node test-core.cjs` tests transition ordering, attendance-only ping eligibility, idempotent ping, separate provider records, replies and persistence-ready state. Browser preview walkthrough is checked separately. Loading the native Chrome sidebar requires the unpacked-extension steps above.

Chrome references: https://developer.chrome.com/docs/extensions/reference/api/sidePanel and https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world
''',
'start-preview.ps1':'''$pythonExe = Join-Path $PSScriptRoot '..\\.venv\\Scripts\\python.exe'
& $pythonExe -m http.server 8766 --bind 127.0.0.1 --directory $PSScriptRoot
''',
 'test-core.cjs':'''const assert=require('node:assert/strict');const c=require('./core.js');let s=c.seed();assert.throws(()=>c.apply(s,'ping'));assert.throws(()=>c.apply(s,'note',{body:'question'}));s=c.apply(s,'attend');s=c.apply(s,'ping');assert.deepEqual(c.apply(s,'ping'),s);s=c.apply(s,'note',{body:'Balance question'});assert.throws(()=>c.apply(s,'reply',{id:1,body:' '}));s=c.apply(s,'reply',{id:1,body:'Follow up before class'});assert.throws(()=>c.apply(s,'reply',{id:1,body:'Duplicate'}));s=c.apply(s,'provider',{provider:'mindbody'});assert.equal(s.sites.mindbody.logs.length,0);assert.equal(s.sites.mindbody.ping,false);s=c.apply(s,'attend');s=c.apply(s,'ping');s=c.apply(s,'note',{body:'Second provider question'});assert.equal(s.sites.gymdesk.logs[0].reply,'Follow up before class');s=c.apply(s,'reset');assert.equal(s.sites.mindbody.logs.length,0);assert.equal(s.sites.gymdesk.logs.length,1);assert.deepEqual(JSON.parse(JSON.stringify(s)),s);assert.throws(()=>c.apply(s,'provider',{provider:'unknown'}));console.log('PASS: ordering, attendance gate, ping idempotency, validation, reply deduplication, provider isolation, reset isolation, serializable state');'''
}
for name,content in files.items(): (p/name).write_text(content,encoding='utf-8')
print(f'Created {len(files)} files in {p}')
