const assert=require('node:assert/strict');
const c=require('./core.js');
const snapshot={memberId:'12672454',memberName:'Sarah Demo',gym:'AKLabs MMA',observedAt:'2026-09-28T17:00:00Z',records:[{id:'62252846',sessionId:'1832536',date:'09/28/2026',when:'Sep 28, 2026 7:00 AM',duration:'1h',title:'Cornerwork Test — Boxing'}]};
const after=new Date(2026,8,28,9).getTime(),before=new Date(2026,8,28,7,30).getTime();
let s=c.apply(c.seed(),'importGymdesk',{snapshot,now:before});
assert.equal(s.sites.gymdeskLive.ping,false);
assert.throws(()=>c.apply(s,'note',{body:'Too early'}));
assert.throws(()=>c.apply(s,'attend'));
assert.throws(()=>c.apply(s,'ping'));
s=c.apply(s,'importGymdesk',{snapshot,now:after});
assert.equal(s.sites.gymdeskLive.ping,true);
s=c.apply(s,'note',{body:'Help with my jab',audio:'data:audio/wav;base64,UklGRg=='});
s=c.apply(s,'reply',{id:1,body:'We will review it next class.'});
s=c.apply(s,'importGymdesk',{snapshot,now:after});
assert.equal(s.sites.gymdeskLive.pingIds.length,1);
assert.equal(s.sites.gymdeskLive.logs.length,1);
assert.equal(s.sites.gymdeskLive.logs[0].attendanceId,'62252846');
assert.equal(s.sites.gymdeskLive.logs[0].reply,'We will review it next class.');
assert.equal(s.sites.gymdesk.logs.length,0);
s=c.apply(s,'importGymdesk',{snapshot:{...snapshot,records:[]},now:after});
assert.equal(s.sites.gymdeskLive.ping,false);
assert.equal(s.sites.gymdeskLive.logs.length,1);
assert.throws(()=>c.apply(s,'note',{body:'No attendance'}));
assert.throws(()=>c.apply(s,'importGymdesk',{snapshot:{...snapshot,memberId:'wrong'}}));
for(const patch of [{date:'02/31/2026'},{when:'Sep 28, 2026 25:00 PM'},{duration:'unknown'}])assert.throws(()=>c.apply(s,'importGymdesk',{snapshot:{...snapshot,records:[{...snapshot.records[0],...patch}]}}));
console.log('PASS: end-of-class gate, no fabricated check-in, repeat import, voice/reply preservation, attendance association, provider isolation, removed attendance, invalid source/date/duration.');
