let recorder=null,stream=null,timer=null,draft='',draftProvider='',previewURL='',pending=false;
const voiceStatus=t=>document.querySelector('#voice-status').textContent=t;
function cleanup(){clearTimeout(timer);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;}
function buttons(){document.querySelector('#record').disabled=pending||!!recorder;document.querySelector('#stop-record').disabled=!recorder||recorder.state!=='recording';document.querySelector('#discard-record').disabled=!draft||pending||!!recorder;document.querySelector('#audio-file').disabled=pending||!!recorder;}
function clearDraft(){draft='';draftProvider='';const a=document.querySelector('#voice-preview');a.pause();a.removeAttribute('src');a.hidden=true;if(previewURL)URL.revokeObjectURL(previewURL);previewURL='';document.querySelector('#audio-file').value='';buttons();}
async function acceptBlob(blob,provider){if(blob.size>800000)throw Error('Clip is too large. Use a shorter recording (max 800 KB).');if(!blob.size)throw Error('The recording is empty. Try again.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read audio.'));r.readAsDataURL(blob)});if(!/^data:audio\/(webm|ogg|mp4|mpeg|wav|x-wav)(;codecs=[^;,]+)?;base64,/.test(data))throw Error('Unsupported audio format. Try WebM, Ogg, M4A, MP3 or WAV.');clearDraft();draft=data;draftProvider=provider;previewURL=URL.createObjectURL(blob);const a=document.querySelector('#voice-preview');a.src=previewURL;a.hidden=false;voiceStatus('Audio ready. Listen, then send to the coach queue. No automatic transcript.');buttons();}
document.querySelector('#record').onclick=async()=>{if(pending||recorder)return;pending=true;buttons();const provider=CW.read().provider;try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Recording is unavailable here. Open in desktop Chrome or choose an audio file.');stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime,audioBitsPerSecond:32000}:{});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>{cleanup();recorder=null;pending=false;buttons();voiceStatus('Recording failed. Try again or choose an audio file.')};recorder.onstop=async()=>{const type=recorder?.mimeType||mime||'audio/webm';cleanup();recorder=null;pending=true;buttons();try{await acceptBlob(new Blob(chunks,{type}),provider)}catch(e){voiceStatus(e.message)}finally{pending=false;buttons()}};recorder.start();pending=false;timer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},45000);voiceStatus('Recording... press Stop when finished (45-second limit).');buttons();}catch(e){cleanup();recorder=null;pending=false;buttons();voiceStatus(e.name==='NotAllowedError'?'Microphone permission was denied. Allow it in browser settings or choose an audio file.':e.message)}};
document.querySelector('#stop-record').onclick=()=>{if(recorder?.state==='recording'){pending=true;recorder.stop();buttons();}};
document.querySelector('#discard-record').onclick=()=>{clearDraft();voiceStatus('Audio discarded. Record another or type a message.')};
document.querySelector('#audio-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;pending=true;buttons();const provider=CW.read().provider;try{await acceptBlob(file,provider)}catch(err){voiceStatus(err.message)}finally{pending=false;buttons()}};
window.addEventListener('pagehide',cleanup);
window.Voice={audio:()=>draft,provider:()=>draftProvider,busy:()=>pending||!!recorder,clear:()=>{clearDraft();voiceStatus('Voice note sent locally.')}};
